config/routes.rb
MoneyMinder::Application.routes.draw do
  post  'purchases' => 'purchases#create', :as => :purchases
  post  'expected_purchase/:id/purchases' => 'purchases#create_from_expected_purchase', :as => :expected_purchase_purchases
  get   'purchases/new' => 'purchases#new', :as => :new_purchase
  get   'purchases/:id' => 'purchases#show', :as => :purchase
  
  get   'transfers' => 'transfers#dash', :as => :transfers_dash
  get   'transfers/:id' => 'transfers#show', :as => :transfer
  get   'virtual_transfers/:id' => 'virtual_transfers#show', :as => :virtual_transfer
  
  get   'accounts' => 'accounts#index', :as => :accounts
  get   'accounts/new' => 'accounts#new', :as => :new_account
  get   'accounts/:name' => 'accounts#show', :as => :account

  get   'virtual_accounts' => 'virtual_accounts#index', :as => :virtual_accounts
  post  'virtual_accounts' => 'virtual_accounts#create'
  get   'virtual_accounts/new' => 'virtual_accounts#new', :as => :new_virtual_account
  get   'virtual_accounts/:name' => 'virtual_accounts#show', :as => :virtual_account
  get   'virtual_account/:name/purchases/new' => 'purchases#new_from_virtual_account', :as => :new_purchase_from_virtual_account

  get     'expected_purchases' => 'expected_purchases#index', :as => :expected_purchases
  get     'expected_purchase/:id/purchase/new' => 'purchases#new_from_expected_purchase', :as => :new_purchase_from_expected_purchase
  delete  'expected_purchase/:id' => 'expected_purchases#dismiss', :as => :expected_purchase

  get   'expected_revenues' => 'expected_revenues#index', :as => :expected_revenues
  get   'expected_revenues/:id/revenues/new' => 'revenues#new_from_expected_revenue', :as => :new_revenue_from_expected_revenue

  post  'revenues' => 'revenues#create', :as => :revenues
  get   'revenues' => 'revenues#index'
  get   'revenues/new' => 'revenues#new', :as => :new_revenue
  get   'revenues/:id'  => 'revenues#show', :as => :revenue
  
  get   'vendors' => 'vendors#index', :as => :vendors
  get   'vendors/new' => 'vendors#new', :as => :new_vendor
  get   'vendors/:name' => 'vendors#show', :as => :vendor, :name => /[^\/]+/
  post  'vendors' => 'vendors#create'

  get   'customers' => 'customers#index', :as => :customers
  get   'customers/new' => 'customers#new', :as => :new_customer
  get   'customers/:name' => 'customers#show', :as => :customer, :name => /[^\/]+/
  post  'customers' => 'customers#create'
  
  get   'revenue_recipes' => 'revenue_recipes#index', :as => :revenue_recipes
  get   'revenue_recipes/new' => 'revenue_recipes#new', :as => :new_revenue_recipe
  get   'revenue_recipes/:id' => 'revenue_recipes#show', :as => :revenue_recipe
  get   'revenue_recipes/:id/edit' => 'revenue_recipes#edit', :as => :revenue_recipe_edit
  post  'revenue_recipes' => 'revenue_recipes#create'
  

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  
  def new
    PurchaseRecipe.schedule_all
  end
  
  def show
    @transaction = Purchase.find(params[:id])
    @virtual_transactions = @transaction.virtual_purchases
    respond_to do |format|
      format.html {}
      format.js { render :partial => 'virtual_transactions' }
    end
  end
  
  def new_from_virtual_account
    @virtual_account = VirtualAccount.find_by_name(params[:name])
    @spending_accounts = Account.spending_accounts
    @vendors = Vendor.all
    @purchase = Purchase.new_from_virtual_account(@virtual_account)
  end
  
  def new_from_expected_purchase
    @expected_purchase = ExpectedPurchase.find_by_id(params[:id])
    kick_out and return if @expected_purchase.nil?
    @virtual_account = @expected_purchase.virtual_account
    @spending_accounts = Account.spending_accounts
    @vendors = Vendor.all
    @purchase = Purchase.new_from_expected_purchase(@expected_purchase)

    render 'new_from_virtual_account'
  end
  
  def create
    if @purchase = Purchase.create(params[:purchase])
      respond_to do |format|
        format.html {
          flash[:notice] = "Purchase saved: #{purchase_amounts_in_words_from(@purchase)}."
          redirect_to new_purchase_path
        }
        # format.json { render :status => 201, :json => @purchase.to_json(:include => vendor) }
      end
    else
      respond_to do |format|
        format.html {
          @virtual_account = @expected_purchase.virtual_account
          @spending_accounts = Account.spending_accounts
          @payees = Vendor.all
          flash[:error] = 'Could not save purchase because of errors'
          render 'new_from_expected_purchase'
        }
        # format.json { render :status => 400, :json => @purchase.errors.to_json }
      end
    end
  end
  
  private
  
  def kick_out
    flash[:notice] = 'That transaction has been completed!'
    redirect_to :action => 'new'
  end
  
  def purchase_amounts_in_words_from(purchase)
    purchase.virtual_purchases.map{ |vp| "$#{vp.amount} from '#{vp.account_from.name}'" }.join(' and ')
  end
end

app/views/purchases/new.html.haml
%h2 Expected Purchases
%section#expected_purchases
  %p.subtitle Loading expected transactions

%h2 Virtual Accounts
%section#virtual_accounts
  %p.subtitle Loading virtual accounts
  
:css  
  a.icon { 
    display: block;
    width: 100%;
    height: 44px;
    margin: 0;
    border-bottom: 1px solid gray;
    text-align: left;
    background: url(/images/disclosure.png) center right no-repeat;
  }
  p {
    margin: 0.5em 0;
  }
  a.icon p {
    margin: 0;
    padding-top: 1px;
    padding-bottom: 1px;
  }
  p.label {
    font-weight: bold;
    padding-left: 5px;
  }
  p.label span {
    padding-left: .2em;
    font-size: .8em;
  }
  .danger {
    color: red;
  }
  p.subtitle {
    font-weight: normal;
    font-size: 0.9em;
    color: gray;
    padding-left: 5px;
  }
  a { text-decoration: none; color: black; cursor: pointer; }
  a:hover { background-color: #cccccc; }
  a button { height: 70%; margin-top: .7em; float: left; font-weight: bold; color: red; }
  .weak { font-size: .8em; opacity: .5; font-weight: normal; }


:javascript
  $(function () {
    $.get('#{expected_purchases_path}.json', function(json) {
      if(json.length) $('#expected_purchases').html('');
      else $('#expected_purchases p.subtitle').html('There are no expected transactions.');
      var link, name, subtitle, vendor, amount, due_in, delete_button;
      $.each(json, function(i, pur) { 
        link = $('<a>').addClass('icon').attr('href', pur['new_purchase_url']);
        name = $('<p>').addClass('label').html(pur['name']);
        if(pur['is_promised']) {
          due_phrase = 'Due ' + pur['due_in'] + ' - ' + pur['scheduled_on'];
          name.addClass(pur['status']);
        } else {
          due_phrase = pur['due_in'] + ' - ' + pur['scheduled_on'];
        }
        delete_button = $('<button>').attr('id', 'expected_purchase_dismiss_' + pur['id']).html('Dismiss');
        due_in = $('<span class="weak">').html('(' + due_phrase + ')');
        vendor = pur['vendor_name'];
        if(vendor.length) vendor = ' to ' + vendor;
        amount = pur['amount']['currency']['symbol'] + pur['amount']['cents'].toString().replace(/([\d]{2})$/, '.$1')
        if(amount.length > 6) amount = amount.replace(/\.\d*$/, '');
        subtitle = $('<p>').addClass('subtitle').html(amount + vendor);
        link.appendTo('#expected_purchases');
        delete_button.appendTo(link);
        delete_button.click(function(e) {
          e.stopPropagation();
          e.preventDefault();
          if(pur['is_promised'] && !confirm('Are you sure?')) return;
          var form = $('<form>').attr('action', pur['dismiss_url']).attr('method', 'post');
          $('<input>').attr('name', '_method').val('delete').appendTo(form);
          $('<input>').attr('name', 'authenticity_token').val('#{form_authenticity_token}').appendTo(form);
          form.submit();
        })
        name.appendTo(link);
        due_in.appendTo(name);
        subtitle.appendTo(link);
      });
    });

    function Money(cents) {
      this.dollars = parseFloat(cents) / 100;
      this.toString = function() {
          var str = '$' + this.dollars.toString();
          str = str.replace(/^(\$[\d]*)$/, '$1.00');
          str = str.replace(/(\.[\d])$/, '$10');
          if(this.dollars < 0) str = '(' + str + ')';
          return str;
      };
      this.isNegative = function() { return this.dollars < 0; };
    }
    $.get('#{virtual_accounts_path}.json', function(json) {
      if(json.length) $('#virtual_accounts').html('');
      else $('#virtual_accounts p.subtitle').html('There are no accounts to show.');
      var link, name, subtitle, account_link, balance, balanceSpan;
      $.each(json, function(i, acct) { 
        link = $('<a>').addClass('icon').attr('href', new_purchase_from_virtual_account_path(acct));
        name = $('<p>').addClass('label').html(acct['name']);
        balance = new Money(acct['balance']['cents']);
        balanceSpan = $('<span>').html(balance.toString());
        subtitle = $('<p>').addClass('subtitle');
        balanceSpan.appendTo(subtitle);
        if(balance.isNegative()) balanceSpan.addClass('negative');
        link.appendTo('#virtual_accounts');
        name.appendTo(link);
        subtitle.appendTo(link);
      });
    });
  });

app/views/purchases/new_from_virtual_account.html.haml
%style
  h1 a { font-size: inherit; }
%h1
  = link_to @virtual_account.name, virtual_account_path(@virtual_account)
  = "(#{@expected_purchase.recipe.name})" if @expected_purchase
%p== Virtual account balance: $#{@virtual_account.balance}

= form_for @purchase do |pur|
  = pur.hidden_field :expected_purchase_id
  = pur.fields_for :virtual_purchases do |vt|
  
    %div.erase_all
      = vt.text_field :amount, :type => :number, :step => '0.01', :min => '0.00', :placeholder => 'Amount'
      %span.erase_all X
    
    %div
      = pur.text_field :memo, :placeholder => 'Memo'
      
      = vt.hidden_field :account_from_id
      
    %div
      = pur.text_field :executed_at, :type => 'datetime'
      
    :javascript
      $(function() {
        var available_vendors = #{@vendors.map(&:name).to_json.html_safe};
        $('#purchase_vendor_name').autocomplete({
          source: available_vendors
        });
        $('span.erase_all').bind('click', function() { $(this).parent().find('input').val('').focus(); });
        $('div.erase_all').hover(function() {  });
      });
      
    %div.erase_all
      = pur.text_field :vendor_name, :placeholder => 'Payee'
      %span.erase_all X

  %div
    = pur.select :account_from_id, @spending_accounts.map{ |a| [a.name, a.id] }, :selected => @virtual_account.primary_spending_account.id
  
  %label &nbsp;
  %br
  = pur.submit 'Submit'
  
:javascript
  $(function(){
    $('#physical_transaction_virtual_transactions_attributes_0_amount').mouseup(function() { $(this).select(); });
  });

app/views/purchases/show.html.haml
%table
  %tr.transaction
    %td.date= @transaction.executed_at.strftime('%m/%d')
    %td.description= transaction_title_span(@transaction)
    %td.description= transaction_subtitle_span(@transaction)

%h2 Virtual portions
%table.virtual_portions
  - @virtual_transactions.each do |trans|
    %tr{ :class => cycle('odd', 'even') }
      %td.description= trans.inside_account.name
      %td.amount= display_amount(trans)

  %tr{ :class => cycle('odd', 'even') }
    %td
      %strong== TOTAL (#{display_inside_account_name(@transaction)})
    %td.amount= display_amount(@transaction)
      
      
:css
  h2 { margin-top: 1em; }
  th { text-align: left; }
  tr.transaction { background-color: white; cursor: auto; }
  td { border: none; }
  section.virtual_transactions { width: 250px; float: right; }
  section.virtual_transactions table { }
  h2 { width: 290px; }
  table.virtual_portions { width: 290px; }
  table.virtual_portions td { padding: .5em .2em; }