config/routes.rb
MoneyMinder::Application.routes.draw do
  post  'purchases' => 'purchases#create', :as => :purchases
  post  'expected_purchase/:id/purchases' => 'purchases#create_from_expected_purchase', :as => :expected_purchase_purchases
  get   'purchases/new' => 'purchases#new', :as => :new_purchase
  get   'purchases/:id' => 'purchases#show', :as => :purchase
  
  get   'transfers' => 'transfers#dash', :as => :transfers_dash
  get   'transfers/:id' => 'transfers#show', :as => :transfer
  get   'virtual_transfers/:id' => 'virtual_transfers#show', :as => :virtual_transfer
  
  get   'accounts' => 'accounts#index', :as => :accounts
  get   'accounts/new' => 'accounts#new', :as => :new_account
  get   'accounts/:name' => 'accounts#show', :as => :account

  get   'virtual_accounts' => 'virtual_accounts#index', :as => :virtual_accounts
  post  'virtual_accounts' => 'virtual_accounts#create'
  get   'virtual_accounts/new' => 'virtual_accounts#new', :as => :new_virtual_account
  get   'virtual_accounts/:name' => 'virtual_accounts#show', :as => :virtual_account
  get   'virtual_account/:name/purchases/new' => 'purchases#new_from_virtual_account', :as => :new_purchase_from_virtual_account

  get     'expected_purchases' => 'expected_purchases#index', :as => :expected_purchases
  get     'expected_purchase/:id/purchase/new' => 'purchases#new_from_expected_purchase', :as => :new_purchase_from_expected_purchase
  delete  'expected_purchase/:id' => 'expected_purchases#dismiss', :as => :expected_purchase

  get   'expected_revenues' => 'expected_revenues#index', :as => :expected_revenues
  get   'expected_revenues/:id/revenues/new' => 'revenues#new_from_expected_revenue', :as => :new_revenue_from_expected_revenue

  post  'revenues' => 'revenues#create', :as => :revenues
  get   'revenues' => 'revenues#index'
  get   'revenues/new' => 'revenues#new', :as => :new_revenue
  get   'revenues/:id'  => 'revenues#show', :as => :revenue
  
  get   'vendors' => 'vendors#index', :as => :vendors
  get   'vendors/new' => 'vendors#new', :as => :new_vendor
  get   'vendors/:name' => 'vendors#show', :as => :vendor, :name => /[^\/]+/
  post  'vendors' => 'vendors#create'

  get   'customers' => 'customers#index', :as => :customers
  get   'customers/new' => 'customers#new', :as => :new_customer
  get   'customers/:name' => 'customers#show', :as => :customer, :name => /[^\/]+/
  post  'customers' => 'customers#create'
  
  get   'revenue_recipes' => 'revenue_recipes#index', :as => :revenue_recipes
  get   'revenue_recipes/new' => 'revenue_recipes#new', :as => :new_revenue_recipe
  get   'revenue_recipes/:id' => 'revenue_recipes#show', :as => :revenue_recipe
  get   'revenue_recipes/:id/edit' => 'revenue_recipes#edit', :as => :revenue_recipe_edit
  post  'revenue_recipes' => 'revenue_recipes#create'
  

end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
  belongs_to  :account_to, :class_name => 'Account'
  belongs_to  :customer
  has_many    :virtual_revenues
  belongs_to  :expected_revenue
  
  accepts_nested_attributes_for :virtual_revenues
  before_save :process_expected_revenue, :if => proc { |p| p.expected_revenue_id }
  before_save :process_revenue
  
  scope     :to_account,    lambda{ |acct| where(:account_to_id => acct.id) }
  
  def initialize(*args)
    super
    self.executed_at ||= Time.now
  end
  
  def self.new_from_expected_revenue(exp_rev)
    revenue = new(:expected_revenue => exp_rev)
    revenue.account_to = exp_rev.recipe.default_inside_account
    revenue.memo = exp_rev.recipe.name
    revenue.amount = exp_rev.recipe.amount
    revenue.customer = exp_rev.recipe.customer
    revenue.build_virtual_revenues
    revenue
  end
  
  def amount=(arg)
    @amount = Money.from_string(arg.to_f.to_s)
  end
  
  def amount
    @amount ||= virtual_revenues.sum(&:amount)
  end
  
  def build_virtual_revenues
    expected_revenue.recipe.virtual_portions.each do |virtual_portion|
      self.virtual_revenues.build(:account_to => virtual_portion.virtual_account, :cents => virtual_portion.cents)
    end
    expected_revenue.unused_virtual_accounts.each do |virtual_account|
      self.virtual_revenues.build(:account_to => virtual_account, :cents => 0)
    end
  end
  
  def spill_over_virtual_revenue
    remaining_cents = expected_revenue.recipe.cents - expected_revenue.recipe.virtual_portions.sum(:cents)
    VirtualRevenue.new(:account_to => expected_revenue.recipe.spill_over_virtual_account, :cents => remaining_cents)
  end
    
  def process_expected_revenue
    expected_revenue.recipe.virtual_portions.each do |virtual_portion|
      self.virtual_revenues = self.virtual_revenues.select{ |vr| vr.amount > Money.new(0) }
      virtual_amounts = virtual_revenues.map(&:amount).sum
      if (overage = amount - virtual_amounts ) > Money.new(0)
        add_amount_to_spill_over_virtual_revenue(overage)
      end
    end
  end
  
  def process_revenue
    self.virtual_revenues = self.virtual_revenues.select{ |vr| vr.amount > Money.new(0) }
  end
  
  def add_amount_to_spill_over_virtual_revenue(overage)
    find_or_build_spill_over_virtual_revenue.amount += overage
  end
  
  # Assumes that expected_revenue exists
  def find_or_build_spill_over_virtual_revenue
    spill_over_account = expected_revenue.recipe.spill_over_virtual_account
    
    virtual_revenues.select{ |vp| vp.account_to == spill_over_account }.first ||
      virtual_revenues.build(:account_to => spill_over_account, :amount => 0)
  end
  
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  def index
    RevenueRecipe.schedule_all
  end
  
  def new
    @customers = Customer.all
    @holding_accounts = Account.holding_accounts
    @revenue = Revenue.new
    @virtual_accounts = VirtualAccount.all
    4.times { @revenue.virtual_revenues.build }
  end
  
  def new_from_expected_revenue
    @expected_revenue = ExpectedRevenue.outstanding.find_by_id(params[:id])
    kick_out and return if @expected_revenue.nil?
    @holding_accounts = Account.holding_accounts
    @customers = Customer.all
    @revenue = Revenue.new_from_expected_revenue(@expected_revenue)
  end
  
  def show
    @transaction = Revenue.find(params[:id])
    @virtual_transactions = @transaction.virtual_revenues
    
    render 'purchases/show'
  end
  
  def create
    @revenue = Revenue.new(params[:revenue])
    if @revenue.save
      flash[:notice] = "Revenue transaction for $#{@revenue.amount} saved"
      redirect_to accounts_path
    else
      flash[:error] = 'Could not save revenue transaction because of errors'
      @holding_accounts = Account.holding_accounts
      if @revenue.expected_revenue
        @expected_revenue = @revenue.expected_revenue
        render 'new'
      else
        @virtual_accounts = @revenue.virtual_revenues.map(&:account_to)
        render 'new_from_expected_revenue'
      end
    end
  end
  
  def kick_out
    redirect_to :new_purchase
  end
end

app/views/revenues/index.html.haml
%h2 Expected Revenues
%section#expected_revenues
  %p.subtitle Loading expected transactions

:javascript
  $(function () {
    $.get('#{expected_revenues_path}.json', function(json) {
      if(json.length) $('#expected_purchases').html('');
      else $('#expected_purchases p.subtitle').html('There are no expected transactions.');
      var link, name, subtitle, vendor, amount, due_in, delete_button;
      $.each(json, function(i, pur) { 
        link = $('<a>').addClass('icon').attr('href', pur['new_purchase_url']);
        name = $('<p>').addClass('label').html(pur['name']);
        if(pur['is_promised']) {
          due_phrase = 'Due ' + pur['due_in'] + ' - ' + pur['scheduled_on'];
          name.addClass(pur['status']);
        } else {
          due_phrase = pur['due_in'] + ' - ' + pur['scheduled_on'];
        }
        delete_button = $('<button>').attr('id', 'expected_purchase_dismiss_' + pur['id']).html('Dismiss');
        due_in = $('<span class="weak">').html('(' + due_phrase + ')');
        vendor = pur['vendor_name'];
        if(vendor.length) vendor = ' to ' + vendor;
        amount = pur['amount']['currency']['symbol'] + pur['amount']['cents'].toString().replace(/([\d]{2})$/, '.$1')
        if(amount.length > 6) amount = amount.replace(/\.\d*$/, '');
        subtitle = $('<p>').addClass('subtitle').html(amount + vendor);
        link.appendTo('#expected_purchases');
        delete_button.appendTo(link);
        delete_button.click(function(e) {
          e.stopPropagation();
          e.preventDefault();
          if(pur['is_promised'] && !confirm('Are you sure?')) return;
          var form = $('<form>').attr('action', pur['dismiss_url']).attr('method', 'post');
          $('<input>').attr('name', '_method').val('delete').appendTo(form);
          $('<input>').attr('name', 'authenticity_token').val('#{form_authenticity_token}').appendTo(form);
          form.submit();
        })
        name.appendTo(link);
        due_in.appendTo(name);
        subtitle.appendTo(link);
      });
    });
  });

app/views/revenues/new.html.haml
%header
  %h1 New Revenue Transactions

= form_for @revenue do |f|

  = f.select :customer_id, @customers.map{ |c| [c.name, c.id] }
  = f.select :account_to_id, @holding_accounts.map{ |acc| [acc.name, acc.id] }
  = f.text_field :executed_at
  
  %table
    %tr.total_amount
      %td.label
        = f.label :amount
        %br
        %span.info
      %td.symbol $
      %td.amount= f.text_field :amount, :class => :amount

    - @revenue.virtual_revenues.each do |virtual_revenue|
      = f.fields_for :virtual_revenues, virtual_revenue do |vr|
        %tr.virtual_amount
          %td.label= vr.select :account_to_id, @virtual_accounts.map{ |va| [va.name, va.id] }
          %td.symbol $
          %td.amount= vr.text_field :amount, :class => :amount
          
    %tr.submit
      %td
      %td
      %td= f.submit 'Save'
          
:css
  td { text-align: right; padding: .3em 0; }
  td.label { width: 50%; padding-right: 1.2em; }
  td.symbol { width: .3em; font-size: 1.2em; padding-left: 0; padding-right: 0; }
  td.amount { padding: 0; text-align: left; width: 40%; }
  td.amount input { text-align: right; }
  td.label span.info { display: block; padding-right: .2em; font-size: .8em; color: red; }

:javascript
  $(function() {
    record_original_amounts();
    //$.fn.centsValue(function(arg) {
    //  if(arg) {
    //    $(this).val(arg.toString().replace(/([\d]{2})$/, '.$1'));
    //  } else {
    //    parseInt($(this).val.replace(/\./));
    //  }
    //});
    $('td.amount input').bind('change keyup', function() { recalculate_totals(); })
    function recalculate_totals() {
      var total_amount = parseInt($('tr.total_amount input').val().replace(/\./, '')); //$('tr.total_amount input').centsValue();
      var total_of_virtuals = sum_of_virtual_amounts();
      $('tr.spill_over_amount input').val((total_amount - total_of_virtuals).toString().replace(/([\d]{2})$/, '.$1'));
    }
    function sum_of_virtual_amounts() {
      var mySum = 0;
      var initialValueInfoSpan;
      $('tr.virtual_amount input.amount').each(function() {
        mySum += parseInt($(this).val().replace(/\./, ''));
      });
      $('input.amount').each(function() {
        initialValueInfoSpan = $(this).parents('tr').find('td.label span.info');
        if($(this).val() != $(this).attr('attr-original')) {
          initialValueInfoSpan.html('(was ' + $(this).attr('attr-original') + ')');
        } else {
          $(this).parents('tr').find('td.label span.info').html('');
        }
      });
      return mySum;
    }
    function record_original_amounts() {
      $('input').each(function() {
        $(this).attr('attr-original', $(this).val());
      });
    }
  });

app/views/revenues/new_from_expected_revenue.html.haml
%header
  %h1== #{@expected_revenue.recipe.name}
  %p== for #{@expected_revenue.scheduled_on.strftime('%b %d, %Y')}

= form_for @revenue do |f|

  = f.hidden_field :expected_revenue_id
  
  %table
    %tr.total_amount
      %td.label
        = f.label :total_amount
        %br
        %span.info
      %td.symbol $
      %td.amount= f.text_field :total_amount, :class => :amount

    - @revenue.virtual_revenues.each do |virtual_revenue|
      = f.fields_for :virtual_revenues, virtual_revenue do |vr|
        %tr.virtual_amount
          %td.label
            = vr.label :amount, virtual_revenue.account_to.name
            %br
            %span.info
          %td.symbol $
          %td.amount= vr.text_field :amount, :class => :amount
          = vr.hidden_field :account_to_id
          
    = f.fields_for :virtual_revenues, @revenue.spill_over_virtual_revenue do |vr|
      %tr.spill_over_amount
        %td.label
          = vr.label :amount, @revenue.spill_over_virtual_revenue.account_to.name
          %br
          %span.info
        %td.symbol $
        %td.amount= vr.text_field :amount, :disabled => true, :class => :amount
          
:css
  td { text-align: right; padding: .3em 0; }
  td.label { width: 50%; padding-right: 1.2em; }
  td.symbol { width: .3em; font-size: 1.2em; padding-left: 0; padding-right: 0; }
  td.amount { padding: 0; text-align: left; width: 40%; }
  td.amount input { text-align: right; }
  td.label span.info { display: block; padding-right: .2em; font-size: .8em; color: red; }

:javascript
  $(function() {
    record_original_amounts();
    //$.fn.centsValue(function(arg) {
    //  if(arg) {
    //    $(this).val(arg.toString().replace(/([\d]{2})$/, '.$1'));
    //  } else {
    //    parseInt($(this).val.replace(/\./));
    //  }
    //});
    $('td.amount input').bind('change keyup', function() { recalculate_totals(); })
    function recalculate_totals() {
      var total_amount = parseInt($('tr.total_amount input').val().replace(/\./, '')); //$('tr.total_amount input').centsValue();
      var total_of_virtuals = sum_of_virtual_amounts();
      $('tr.spill_over_amount input').val((total_amount - total_of_virtuals).toString().replace(/([\d]{2})$/, '.$1'));
    }
    function sum_of_virtual_amounts() {
      var mySum = 0;
      var initialValueInfoSpan;
      $('tr.virtual_amount input.amount').each(function() {
        mySum += parseInt($(this).val().replace(/\./, ''));
      });
      $('input.amount').each(function() {
        initialValueInfoSpan = $(this).parents('tr').find('td.label span.info');
        if($(this).val() != $(this).attr('attr-original')) {
          initialValueInfoSpan.html('(was ' + $(this).attr('attr-original') + ')');
        } else {
          $(this).parents('tr').find('td.label span.info').html('');
        }
      });
      return mySum;
    }
    function record_original_amounts() {
      $('input').each(function() {
        $(this).attr('attr-original', $(this).val());
      });
    }
  });