config/routes.rb
MoneyMinder::Application.routes.draw do
  post  'purchases' => 'purchases#create', :as => :purchases
  post  'expected_purchase/:id/purchases' => 'purchases#create_from_expected_purchase', :as => :expected_purchase_purchases
  get   'purchases/new' => 'purchases#new', :as => :new_purchase
  get   'purchases/:id' => 'purchases#show', :as => :purchase
  
  get   'transfers' => 'transfers#dash', :as => :transfers_dash
  get   'transfers/:id' => 'transfers#show', :as => :transfer
  get   'virtual_transfers/:id' => 'virtual_transfers#show', :as => :virtual_transfer
  
  get   'accounts' => 'accounts#index', :as => :accounts
  get   'accounts/new' => 'accounts#new', :as => :new_account
  get   'accounts/:name' => 'accounts#show', :as => :account

  get   'virtual_accounts' => 'virtual_accounts#index', :as => :virtual_accounts
  post  'virtual_accounts' => 'virtual_accounts#create'
  get   'virtual_accounts/new' => 'virtual_accounts#new', :as => :new_virtual_account
  get   'virtual_accounts/:name' => 'virtual_accounts#show', :as => :virtual_account
  get   'virtual_account/:name/purchases/new' => 'purchases#new_from_virtual_account', :as => :new_purchase_from_virtual_account

  get     'expected_purchases' => 'expected_purchases#index', :as => :expected_purchases
  get     'expected_purchase/:id/purchase/new' => 'purchases#new_from_expected_purchase', :as => :new_purchase_from_expected_purchase
  delete  'expected_purchase/:id' => 'expected_purchases#dismiss', :as => :expected_purchase

  get   'expected_revenues' => 'expected_revenues#index', :as => :expected_revenues
  get   'expected_revenues/:id/revenues/new' => 'revenues#new_from_expected_revenue', :as => :new_revenue_from_expected_revenue

  post  'revenues' => 'revenues#create', :as => :revenues
  get   'revenues' => 'revenues#index'
  get   'revenues/new' => 'revenues#new', :as => :new_revenue
  get   'revenues/:id'  => 'revenues#show', :as => :revenue
  
  get   'vendors' => 'vendors#index', :as => :vendors
  get   'vendors/new' => 'vendors#new', :as => :new_vendor
  get   'vendors/:name' => 'vendors#show', :as => :vendor, :name => /[^\/]+/
  post  'vendors' => 'vendors#create'

  get   'customers' => 'customers#index', :as => :customers
  get   'customers/new' => 'customers#new', :as => :new_customer
  get   'customers/:name' => 'customers#show', :as => :customer, :name => /[^\/]+/
  post  'customers' => 'customers#create'
  
  get   'revenue_recipes' => 'revenue_recipes#index', :as => :revenue_recipes
  get   'revenue_recipes/new' => 'revenue_recipes#new', :as => :new_revenue_recipe
  get   'revenue_recipes/:id' => 'revenue_recipes#show', :as => :revenue_recipe
  get   'revenue_recipes/:id/edit' => 'revenue_recipes#edit', :as => :revenue_recipe_edit
  post  'revenue_recipes' => 'revenue_recipes#create'
  

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MoneyMinder
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag('iphone', :media => :screen) unless @iphone.nil?
    = stylesheet_link_tag params[:controller], :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag params[:controller]
    = csrf_meta_tags
    %meta{ :name => "viewport", :content => 'width=device-width', 'initial-scale' => '1', 'maximum-scale' => '1', 'user-scalable' => '0' }
    = "<style>body{ width: 600px; margin: auto; }</style>".html_safe if @iphone.nil? 
    
  %body
    %p.notice= notice
    %p.alert= alert
    %p.error= flash[:error]
    
    %header
      %nav
        %ul
          %li.transfers= link_to content_tag(:span, 'Transfers'), transfers_dash_path
          %li.payments= link_to content_tag(:span, 'Purchases'), new_purchase_path
          %li.revenues= link_to content_tag(:span, 'Revenues'), revenues_path
          %li.vendors= link_to content_tag(:span, 'Vendors'), vendors_path
          %li.customers= link_to content_tag(:span, 'Accounts'), accounts_path
          
    = yield

:css
  header { 
    height: 64px; 
    background-color: black;
    color: #dddddd;
    width: 100%;
    /*
    position: fixed;
    top: 400px; 
    */
  }
  header nav ul { 
    padding: 0; 
    margin: 0; 
  }
  header nav ul li {
    position: relative;
    display: block;
    width: 64px;
    height: 64px;
    float: left;
    padding: 0;
    margin: 0;
    font-size: .85em;
    text-align: center;
    border-right: 1px solid #444444;
  }
  header nav ul li a {
    display: block;
    height: 100%;
    width: 100%;
    color: inherit;
  }
  header nav ul li a span {
    display: block;
    position: absolute;
    bottom: 0;
    width: 100%;
  }
  header nav ul li a:hover {
    background-color: black;
  }
  
:javascript
  function Currency(cents) {
    this.dollars = parseFloat(cents) / 100;
  }
 