config/routes.rb
MoneyMinder::Application.routes.draw do
  post  'purchases' => 'purchases#create', :as => :purchases
  post  'expected_purchase/:id/purchases' => 'purchases#create_from_expected_purchase', :as => :expected_purchase_purchases
  get   'purchases/new' => 'purchases#new', :as => :new_purchase
  get   'purchases/:id' => 'purchases#show', :as => :purchase
  
  get   'transfers' => 'transfers#dash', :as => :transfers_dash
  get   'transfers/:id' => 'transfers#show', :as => :transfer
  get   'virtual_transfers/:id' => 'virtual_transfers#show', :as => :virtual_transfer
  
  get   'accounts' => 'accounts#index', :as => :accounts
  get   'accounts/new' => 'accounts#new', :as => :new_account
  get   'accounts/:name' => 'accounts#show', :as => :account

  get   'virtual_accounts' => 'virtual_accounts#index', :as => :virtual_accounts
  post  'virtual_accounts' => 'virtual_accounts#create'
  get   'virtual_accounts/new' => 'virtual_accounts#new', :as => :new_virtual_account
  get   'virtual_accounts/:name' => 'virtual_accounts#show', :as => :virtual_account
  get   'virtual_account/:name/purchases/new' => 'purchases#new_from_virtual_account', :as => :new_purchase_from_virtual_account

  get     'expected_purchases' => 'expected_purchases#index', :as => :expected_purchases
  get     'expected_purchase/:id/purchase/new' => 'purchases#new_from_expected_purchase', :as => :new_purchase_from_expected_purchase
  delete  'expected_purchase/:id' => 'expected_purchases#dismiss', :as => :expected_purchase

  get   'expected_revenues' => 'expected_revenues#index', :as => :expected_revenues
  get   'expected_revenues/:id/revenues/new' => 'revenues#new_from_expected_revenue', :as => :new_revenue_from_expected_revenue

  post  'revenues' => 'revenues#create', :as => :revenues
  get   'revenues' => 'revenues#index'
  get   'revenues/new' => 'revenues#new', :as => :new_revenue
  get   'revenues/:id'  => 'revenues#show', :as => :revenue
  
  get   'vendors' => 'vendors#index', :as => :vendors
  get   'vendors/new' => 'vendors#new', :as => :new_vendor
  get   'vendors/:name' => 'vendors#show', :as => :vendor, :name => /[^\/]+/
  post  'vendors' => 'vendors#create'

  get   'customers' => 'customers#index', :as => :customers
  get   'customers/new' => 'customers#new', :as => :new_customer
  get   'customers/:name' => 'customers#show', :as => :customer, :name => /[^\/]+/
  post  'customers' => 'customers#create'
  
  get   'revenue_recipes' => 'revenue_recipes#index', :as => :revenue_recipes
  get   'revenue_recipes/new' => 'revenue_recipes#new', :as => :new_revenue_recipe
  get   'revenue_recipes/:id' => 'revenue_recipes#show', :as => :revenue_recipe
  get   'revenue_recipes/:id/edit' => 'revenue_recipes#edit', :as => :revenue_recipe_edit
  post  'revenue_recipes' => 'revenue_recipes#create'
  

end

app/models/account.rb
require 'acts_as_account'

class Account < ActiveRecord::Base
  acts_as_account
  
  belongs_to  :holding_account, :class_name => 'Account'
  
  has_many    :purchases,     :foreign_key => :account_from_id, :class_name => 'Purchase'
  has_many    :revenues,      :foreign_key => :account_to_id,   :class_name => 'Revenue'
  has_many    :transfers_to,  :foreign_key => :account_to_id,   :class_name => 'Transfer'
  has_many    :transfers_from,:foreign_key => :account_from_id, :class_name => 'Transfer'
  
  scope :spending_accounts, where(:is_spending => true)
  scope :holding_accounts,  where(:is_holding  => true)

  #  TODO: Revenue and Purchase amounts are the SUMs of their virtual_revenues and virtual_purchases
  #        Will require a join in each case and probably .sum('"virtual_revenues"."cents"') etc.
  def balance
    Money.new(
      Revenue.to_account(self).joins(:virtual_revenues).sum('"virtual_revenues"."cents"').to_i +
      Transfer.to_account(self).sum(:cents) - Transfer.from_account(self).sum(:cents) - 
      Purchase.from_account(self).joins(:virtual_purchases).sum('"virtual_purchases"."cents"').to_i +
      self.initial_balance_in_cents
    )
  end
  
  def transactions
    [purchases, revenues, transfers_to, transfers_from].flatten.sort{ |x, y| y.executed_at <=> x.executed_at }
  end

  def running_balances
    size = transactions.size
    running_balances = Array.new(size + 1)
    (transactions.reverse).each_with_index do |trans, i|
      last_balance = running_balances[size-i] || self.initial_balance
      if trans.respond_to?(:account_from) && trans.account_from == self
        running_balances[size-i-1] = last_balance - trans.amount
      elsif trans.respond_to?(:account_to) && trans.account_to == self
        running_balances[size-i-1] = last_balance + trans.amount
      end
    end
    running_balances
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
    @virtual_accounts = VirtualAccount.all
  end
  
  def show
    @account = Account.find_by_name(params[:name])
  end
  
  def new
    @account = Account.new
    @holding_accounts = Account.holding_accounts
  end
end

app/views/accounts/index.html.haml
%h2 
  Physical Accounts
  &nbsp;
  = link_to '+', new_account_path
  
%section#accounts
  - @accounts.each do |acct|
  
    %a.icon{ :href => account_path(acct) }
      %p.label= acct.name
      %p.subtitle== $#{acct.balance}
      
  .clear
  
%h2 
  Virtual Accounts
  &nbsp;
  = link_to '+', new_virtual_account_path

%section#virtual_accounts
  - @virtual_accounts.each do |acct|
    
    %a.icon{ :href => virtual_account_path(acct) }
      %p.label= acct.name
      %p.subtitle== $#{acct.balance}

:css  
  a.icon { 
    display: block;
    float: left;
    width: 146px;
    height: 55px;
    margin: 1px;
    border: 1px solid gray;
    border-radius: .5em;
    text-align: left;
  }
  p {
    margin: 0.5em 0;
    font-size: .9em;
  }
  a.icon p {
    margin: 0;
    padding-top: 1px;
    padding-bottom: 1px;
  }
  p.label {
    font-weight: bold;
    padding-left: 5px;
  }
  p.label span {
    padding-left: .2em;
    font-size: .8em;
  }
  .danger {
    color: red;
  }
  p.subtitle {
    font-weight: normal;
    font-size: 0.9em;
    color: gray;
    padding-left: 5px;
  }
  a { text-decoration: none; color: black; cursor: pointer; }
  a:hover { background-color: #cccccc; }
  a button { height: 70%; margin-top: .7em; float: left; font-weight: bold; color: red; }
  .weak { font-size: .8em; opacity: .5; font-weight: normal; }

app/views/accounts/new.html.haml
%h2== New#{@account.class.to_s.gsub(/([A-Z])/, ' \1')}

= form_for @account do |f|
  %div
    = f.text_field :name, :placeholder => 'Name'
  
  - if @account.respond_to? :is_spending
    %div
      = f.label :is_spending, 'Spending?', :class => 'checkbox'
      = f.check_box :is_spending, :class => 'checkbox'

  - if @account.respond_to? :is_holding
    %div
      = f.label :is_holding, 'Holding?', :class => 'checkbox'
      = f.check_box :is_holding, :class => 'checkbox'
    
  - if @account.respond_to? :holding_account_id
    %div
      = f.select :holding_account_id, @holding_accounts.map{ |a| [a.name, a.id] }, :include_blank => '- Select holding account -'

  - if @account.respond_to? :primary_spending_account_id
    %div
      = f.select :primary_spending_account_id, @spending_accounts.map{ |a| [a.name, a.id] }, :include_blank => '- Select primary spending account -'
  
  %div
    = f.label :initial_balance
    = f.text_field :initial_balance, :type => :number, :step => '0.01', :min => '0.00', :placeholder => 'Initial balance'
    
  %div
    = f.submit

app/views/accounts/show.html.haml
%h1
  = @account.name
  - if @account.is_a? VirtualAccount
    = link_to 'Make new purchase', new_purchase_from_virtual_account_path(@account)
  
%table
  %tr
    %th Date
    %th Description
    %th Amount
    - if @iphone.nil?
      %th Balance

  - @account.transactions.each_with_index do |trans, i|
    %tr.transaction{ :class => cycle('odd', 'even'), 'attr-href' => computed_transaction_path(trans) }
      %td.date= trans.executed_at.strftime '%m/%d'
      %td.description= transaction_description trans, @account.id
      %td.amount= display_amount trans, @account.id
      - if @iphone.nil?
        %td.balance= display_money @account.running_balances[i]

  - if @iphone.nil?  
    %tr{ :class => cycle('odd', 'even') }
      %td
      %td.description
        %span.title Initial Balance
      %td
      %td.balance= display_money @account.initial_balance
      
:css
  tr { height: 2.2em; }

:javascript
  $(function() {
    $('tr.transaction').click(function() {
      window.location = $(this).attr('attr-href');
    });
  });